on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Development Build - ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Rust Dependency Cache
        uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dev release ${{ github.sha }} - ${{ matrix.platform }}
          path: |
            target/release/bonkmarmu-midi-web
            target/release/bonkmarmu-midi-web.exe
